// test-app-angular/src/app/components/tutorial-section.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-tutorial-section',
  standalone: true,
  imports: [NgIf],
  template: `
    <section [class]="'rounded-lg shadow-sm border overflow-hidden ' +
      (completed ? 'bg-green-100 border-green-300' : 'bg-white border-gray-200')">

      <!-- Header -->
      <div class="flex items-center gap-3 px-6 py-4 border-b border-gray-100">
        <span [class]="'flex items-center justify-center w-8 h-8 rounded-full text-sm font-bold shrink-0 ' +
          (completed ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500')">
          <svg *ngIf="completed" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
            <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
          </svg>
          <ng-container *ngIf="!completed">{{ step }}</ng-container>
        </span>

        <h2 class="text-lg font-semibold text-gray-900 flex-1">{{ title }}</h2>

        <span *ngIf="completed" class="text-xs font-medium text-green-600 bg-green-50 px-2 py-1 rounded-full">
          Done
        </span>
      </div>

      <!-- Body -->
      <div class="px-6 py-5">
        <!-- Instructions -->
        <div class="text-sm text-gray-600 leading-relaxed mb-5">
          <ng-content select="[instructions]" />
        </div>

        <!-- Playground -->
        <div [class]="playgroundClassName">
          <ng-content />
        </div>

        <!-- Fallback button -->
        <div *ngIf="!completed" class="mt-4 flex justify-end">
          <button
            (click)="markComplete.emit()"
            class="text-sm text-gray-500 hover:text-gray-700 border border-gray-300 rounded-md px-3 py-1.5 hover:bg-gray-50 transition-colors"
          >
            Mark complete
          </button>
        </div>
      </div>
    </section>
  `,
})
export class TutorialSectionComponent {
  @Input({ required: true }) step!: number;
  @Input({ required: true }) title!: string;
  @Input() completed: boolean = false;
  @Input() playgroundClassName: string = 'border border-gray-200 rounded-lg p-6 bg-gray-50';
  @Output() markComplete = new EventEmitter<void>();
}

// test-app/src/TutorialSection.tsx
interface TutorialSectionProps {
  step: number
  title: string
  completed: boolean
  onMarkComplete: () => void
  children?: React.ReactNode
  instructions: React.ReactNode
  playgroundClassName?: string
}

export function TutorialSection({
  step,
  title,
  completed,
  onMarkComplete,
  children,
  instructions,
  playgroundClassName,
}: TutorialSectionProps) {
  return (
    <section className={`rounded-lg shadow-sm border overflow-hidden ${
      completed
        ? 'bg-green-100 border-green-300'
        : 'bg-white border-gray-200'
    }`}>
      {/* Header */}
      <div className="flex items-center gap-3 px-6 py-4 border-b border-gray-100">
        {/* Step badge */}
        <span
          className={`flex items-center justify-center w-8 h-8 rounded-full text-sm font-bold shrink-0 ${
            completed
              ? 'bg-green-100 text-green-700'
              : 'bg-gray-100 text-gray-500'
          }`}
        >
          {completed ? (
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
            </svg>
          ) : (
            step
          )}
        </span>

        <h2 className="text-lg font-semibold text-gray-900 flex-1">{title}</h2>

        {completed && (
          <span className="text-xs font-medium text-green-600 bg-green-50 px-2 py-1 rounded-full">
            Done
          </span>
        )}
      </div>

      {/* Body */}
      <div className="px-6 py-5">
        {/* Instructions */}
        <div className="text-sm text-gray-600 leading-relaxed mb-5 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mt-2 [&_ol]:space-y-1 [&_strong]:text-gray-900 [&_em]:text-gray-500">
          {instructions}
        </div>

        {/* Playground */}
        {children && (
          <div className={playgroundClassName ?? "border border-gray-200 rounded-lg p-6 bg-gray-50"}>
            {children}
          </div>
        )}

        {/* Fallback button */}
        {!completed && (
          <div className="mt-4 flex justify-end">
            <button
              onClick={onMarkComplete}
              className="text-sm text-gray-500 hover:text-gray-700 border border-gray-300 rounded-md px-3 py-1.5 hover:bg-gray-50 transition-colors"
            >
              Mark complete
            </button>
          </div>
        )}
      </div>
    </section>
  )
}
